### PR TITLE
Add default `rcParams`

### PR DESCRIPTION
**Pull request by iaraota**
This pull request introduces default `rcParams`, ensuring that plots have the desired appearance without the necessity of activating the `ligo-summary-3.10` Conda environment.

These parameters were obtained by comparing the `matplotlib.rcParams` differences between `igwn` and `ligo-summary-3.10` Conda environments.

### CODE REVIEW

**Comment by iaraota** [comment]
@eagoetz  I tested the following:

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl

plt.rcParams["figure.figsize"] = (5,10)
data = np.random.randn(50)
plt.plot(data)
plt.savefig('before_gwsumm.png')
import gwsumm
plt.close('all')
plt.plot(data)
plt.savefig('before_after.png')

```

The saved figures remain unchanged, that is, the "figure.figsize" stays at (5,10) rather than the GWSumm default of (12, 6).

**Comment by eagoetz** [comment]
@iaraota Thanks for trying this out! Have you tried `from gwsumm import plot`? I want to confirm what that does with this PR. Thanks!

Also, I'm not sure what's going on with the CI failures, but it is likely related to this change.

**Comment by iaraota** [comment]
@eagoetz thank you for your suggestion. I tested the following, and the plots remain the same:

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl

plt.rcParams["figure.figsize"] = (5,10)
data = np.random.randn(50)
plt.plot(data)
plt.savefig('before_gwsumm.png')
from gwsumm import plot
plot.DataPlot(['L1:DMT-SNSL_EFFECTIVE_RANGE_MPC'], 1388102418, 1388188818)
plt.close('all')
plt.plot(data)
plt.savefig('before_after.png')

```

I fixed the test. It was checking whether `cp.set('plot', 'figure.figsize', '2, 1')` works. However, since `rcParams` used to be empty, is was asserting the `rcParams` as a dictionary. Now I am testing only the change in `figure.figsize`. By the way, this test also shows that `rcParams` is changeable, as you were concerned it could not be.

**Review by eagoetz — APPROVED** [review]
LGTM

**Pull request merged**
