### PR TITLE
Fix broken docs link

### LINKED ISSUE #179: Link missing on the Tabs API instructions page
From this pages the first link is missing:
https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/gwsumm/latest/tabs/websites.html#websites

More precisely: “As we have seen” which points to: https://ldas-jobs.ligo.caltech.edu/~duncan.macleod/gwsumm/latest/tabs/index

### PR DESCRIPTION
**Pull request by eagoetz**
Closes #179

Simply change the broken link to one that works.

### CODE REVIEW

**Comment by eagoetz** [comment]
@duncanmmacleod What's the procedure for determining if docs changes work properly? 

Also, it looks like https://gwsumm.readthedocs.io/en/latest/ is woefully out of date (0.1.2!). How do we update this?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod What's the procedure for determining if docs changes work properly?
> 
> Also, it looks like https://gwsumm.readthedocs.io/en/latest/ is woefully out of date (0.1.2!). How do we update this?

I have resync'd the webhook used by readthedocs, which seems to have kickstarted the PR builds, which is the way to test the docs changes. This in turn exposes the docs failure responsible for the out-of-date docs.

**Comment by duncanmmacleod** [comment]
See https://github.com/gwpy/gwsumm/pull/343 for a fix to the rtd builds.

**Review by duncanmmacleod — APPROVED** [review]
Verified as works, thanks @eagoetz.

**Pull request merged**
