### PR TITLE
Add a HTMLContentTab class

### PR DESCRIPTION
**Pull request by mattpitkin**
I couldn't find a Tab class that allowed me to create a tab that just contained some user provided HTML and nothing else. I'd added one in the PR @duncanmmacleod @alurban let me know whether what I've done looks OK? I've tested it and it does work.

### CODE REVIEW

**Comment by alurban** [comment]
@mattpitkin, can you clarify the use case you're trying to address? The [**`gwsumm.tabs.builtin.ExternalTab`**](https://github.com/gwpy/gwsumm/blob/master/gwsumm/tabs/builtin.py#L53-L166) allows you to wrap around external HTML, with custom success and failure operations supplied through a configuration file as javascript. An example of that in action can be found in several places under the DetChar tab in the production summary pages, e.g. the [**daily overflow analysis**](https://ldas-jobs.ligo-la.caltech.edu/~detchar/summary/day/20190418/detchar/overflows/) (requires `LIGO.ORG` credentials).

Would this existing tab class serve your purposes? If so, let me know if you want help setting up a config file, it's pretty straightforward. (I prefer not to add redundant functionality if it can be avoided.)

**Comment by mattpitkin** [comment]
@alurban al Thank for the tip. I think the `ExternalTab` should actually cover what I was wanting to do, so I'll give that a try. It might be nice if you could also just pass that tab the HTML to render directly in the ini file, rather than having to give it an external URL or file path.

**Comment by alurban** [comment]
@mattpitkin, sounds good, you _may_ already be able to do that using the `success` argument, something like:

```ini
success = const template = document.createElement('template'); template.content.append(document.createElement('div')); document.head.append(template)
```

etc., though this would probably be a right pain in the you-know-where.

**Comment by mattpitkin** [comment]
I'll close this for now as it's not required.

**Pull request closed without merging**
