### PR TITLE
TimeSeriesHistogram2dDataPlot

### PR DESCRIPTION
**Pull request by maxisi**
Adds a new kind of DataPlot, subclassed from TimeSeriesHistogramDataPlot, that produces 2D histograms for two given channels. An example of the output can be found here: https://ldas-jobs.ligo.caltech.edu/~max.isi/gwsumm_hist2d/day/20151114/

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
hey @maxisi, this looks good, can you point me towards an example of the output?

**Comment by maxisi** [comment]
Good!
https://ldas-jobs.ligo.caltech.edu/%7Emax.isi/gwsumm_hist2d/day/20151114/

**Comment by duncanmmacleod** [comment]
hmmm, on second viewing, I've noticed that you have reproduced the Spectrogram plotting from GWpy, which is fine but you should use `copy=False, sparse=True` when calling `numpy.meshgrid` to cut down on memory and CPU cost, it shouldn't affect the pcolormesh output in any way. Can you switch that and check things still work.

Can you post another example without Gouraud shading as well?

**Comment by maxisi** [comment]
@duncanmmacleod, I have now included the requested `numpy.meshgrid` options (actually, I hadn't noticed this is what you use in Spectrogram; the code is taken from a 40m script).

Here is an example with `shading = flat`:
https://ldas-jobs.ligo.caltech.edu/~max.isi/gwsumm_hist2d/day/20151116/

**Comment by duncanmmacleod** [comment]
that looks much better (imho). I'm also concerned about the Spectral colormap (its designed for divergent datasets), can you throw me an example using one of the sequential colormaps [here](http://matplotlib.org/examples/color/colormaps_reference.html) (ideally a perceptually uniform one, probably in reverse, e.g. `inferno_r`)?

**Comment by maxisi** [comment]
I can definitely change the defaults. Here's an example with `cmap = inferno_r`:
https://ldas-jobs.ligo.caltech.edu/~max.isi/gwsumm_hist2d_2/day/20151116/

**Comment by duncanmmacleod** [comment]
another quick point, you don't need to rotate `h` to pass to pcolormesh, just use `h.T`:

```diff
$ git diff gwsumm/plot/builtin.py 
diff --git a/gwsumm/plot/builtin.py b/gwsumm/plot/builtin.py
index 67c3b6e..41eb27f 100644
--- a/gwsumm/plot/builtin.py
+++ b/gwsumm/plot/builtin.py
@@ -649,13 +649,11 @@ class TimeSeriesHistogram2dDataPlot(TimeSeriesHistogramPlo
         hist_kwargs = self.parse_hist_kwargs()
         h, xedges, yedges = numpy.histogram2d(data[0], data[1],
                                               **hist_kwargs)
-        h = numpy.ma.masked_where(h==0, numpy.flipud(numpy.rot90(h)))
+        h = numpy.ma.masked_where(h==0, h)
         x, y = numpy.meshgrid(xedges[:-1]+numpy.diff(xedges),
                               yedges[:-1]+numpy.diff(yedges),
                               copy=False, sparse=True)
         # plot
         pcmesh_kwargs = self.parse_pcmesh_kwargs()
-        ax.pcolormesh(x, y, h, **pcmesh_kwargs)
+        ax.pcolormesh(x, y, h.T, **pcmesh_kwargs)
         # customise plot
         for key, val in self.pargs.iteritems():
             try:
```

**Comment by duncanmmacleod** [comment]
also, `pcolormesh` assumes `x` and `y` to define the coordinates of quarilaterals from the lower-left corner [[ref](http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.pcolor)] so we shouldn't need to use `numpy.diff`. Can you patch this as follows:

```diff
 git diff gwsumm/plot/builtin.py 
diff --git a/gwsumm/plot/builtin.py b/gwsumm/plot/builtin.py
index 67c3b6e..41eb27f 100644
--- a/gwsumm/plot/builtin.py
+++ b/gwsumm/plot/builtin.py
@@ -649,13 +649,11 @@ class TimeSeriesHistogram2dDataPlot(TimeSeriesHistogramPlo
         hist_kwargs = self.parse_hist_kwargs()
         h, xedges, yedges = numpy.histogram2d(data[0], data[1],
                                               **hist_kwargs)
         h = numpy.ma.masked_where(h==0, numpy.flipud(numpy.rot90(h)))
-        x, y = numpy.meshgrid(xedges[:-1]+numpy.diff(xedges),
-                              yedges[:-1]+numpy.diff(yedges),
-                              copy=False, sparse=True)
+        x, y = numpy.meshgrid(xedges, yedges, copy=False, sparse=True)
         # plot
         pcmesh_kwargs = self.parse_pcmesh_kwargs()
```

**Comment by duncanmmacleod** [comment]
@maxisi please confirm that you've pushed all of the changes I requested?

**Comment by maxisi** [comment]
@duncanmmacleod I believe so

**Comment by duncanmmacleod** [comment]
magic, thanks.

**Pull request merged**
