### PR TITLE
Bump gwbootstrap version

### PR DESCRIPTION
**Pull request by eagoetz**
Update gwbootstrap to the latest version to handle fancybox API changes

### CODE REVIEW

**Review by iaraota — APPROVED** [review]

**Comment by iaraota** [comment]
@eagoetz thank you for working on this. Does this update requires`"gwdetchar >=2.2.4"` in `pyproject.toml`?

**Comment by eagoetz** [comment]
> @eagoetz thank you for working on this. Does this update requires`"gwdetchar >=2.2.4"` in `pyproject.toml`?

@iaraota Yes, good catch! I will update this PR

**Comment by eagoetz** [comment]
Ah, and now the tests fail. Let me check it out

**Comment by eagoetz** [comment]
@iaraota All checks now pass. I think it was an issue that gwdetchar-2.2.4 was not available on conda-forge (because I had not merged the update into the feedstock) but it is there now, so the build passes. I will merge this PR

**Pull request merged**
