### PR TITLE
Rename Axes.grid keyword 'b' to 'visible'

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR updates the keyword arguments to `Axes.grid` in response to an upstream matplotlib change.

### CODE REVIEW

**Comment by eagoetz** [comment]
@duncanmmacleod Thanks, this is helpful. I spotted that this PR also changes some of the `grid(True,...` to `grid(visible=True,...`, which is fine and may not even be necessarily required, but this also misses several other instances of these cases. Can you please check the others are also not missed for consistency? Also check for any instances of `b=False` and `axes(False,...`. Thanks!

**Comment by eagoetz** [comment]
@duncanmmacleod Do you need me to help with this?

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod Do you need me to help with this?

@eagoetz, I am presuming that I am no longer principal maintainer of this project, so was waiting for whomever that is (is that you?) to merge it.

**Comment by eagoetz** [comment]
@duncanmmacleod Yes, I am the lead on maintaining this. My original request is that you basically go through the code and search for other forms of this change for consistency:
> Thanks, this is helpful. I spotted that this PR also changes some of the grid(True,... to grid(visible=True,..., which is fine and may not even be necessarily required, but this also misses several other instances of these cases. Can you please check the others are also not missed for consistency? Also check for any instances of b=False and grid(False,.... Thanks!

I was asking if you need help to find these and make those updates to this PR or if you are able to do that on your own. Let me know if that clarifies the request.

**Comment by duncanmmacleod** [comment]
@eagoetz, sorry, I had missed the first comment that was the context for the second and thought you were just asking whether I needed you to help push the PR through. 🤦🏻‍♂️ 

I'll scour the code to find other calls to `Axes.grid`.

**Comment by eagoetz** [comment]
@duncanmmacleod Ping on this PR. I'd like to close out this PR so, if it helps, I can open a superseding PR that goes through the code and makes the appropriate changes

**Comment by eagoetz** [comment]
Closing this PR as it is now superseded by #383

**Pull request closed without merging**
