### PR TITLE
Handle changes in kwarg defaults in Axes.scatter (take 2)

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR revives #328.

### CODE REVIEW

**Comment by eagoetz** [comment]
@duncanmmacleod Thanks for the revised PR to make this work. A couple items:
- The changes look straightforward fixes.
- Do you have an example to prove this works?
- Can you re-run the CI tests? It looks like a lot of them have failures

Thanks again!

**Comment by duncanmmacleod** [comment]
> @duncanmmacleod Thanks for the revised PR to make this work. A couple items:
> 
> * The changes look straightforward fixes.
> * Do you have an example to prove this works?

No. I will endeavour to remember how to run my own code to generate one...

> * Can you re-run the CI tests? It looks like a lot of them have failures

Done, green CI across the board!
> 
> Thanks again!

**Comment by eagoetz** [comment]
@duncanmmacleod A gentle nudge on this. Waiting for an example to prove this works, if it is possible to generate. Thanks!

**Comment by eagoetz** [comment]
Sorry for the ping @duncanmmacleod, I know you were on holiday. Just checking back with you on the status of this and wanted to make sure it didn't fall off your radar. Thanks

**Comment by robertbruntz** [comment]
A second to Evan's nudge.

**Comment by duncanmmacleod** [comment]
Gents, I've rebased this again, updating the GWpy requirement to 3.0.0, will try and remember how to generate an example.

**Comment by eagoetz** [comment]
> Gents, I've rebased this again, updating the GWpy requirement to 3.0.0, will try and remember how to generate an example.

Hi @duncanmmacleod any progress on this front? Thank you!

**Comment by eagoetz** [comment]
@duncanmmacleod I want to try and get the new release of gwsumm out this week, maybe tomorrow. Do you think that you will be able to address this PR this week? If so, that would be really wonderful. Thanks in advance!

**Comment by eagoetz** [comment]
@duncanmmacleod I'm not sure this is enough to fix the issue. I've copied the changes in this PR and made a summary page for the omicron triggers recently from H1: https://ldas-jobs.ligo-wa.caltech.edu/~evan.goetz/summary/day/20221122/lock/glitches/

In the upper left plot, the triggers with higher SNR are still being obscured by the lower SNR triggers. 😞 Somehow the sorting is still not working properly

**Review by eagoetz — APPROVED** [review]
LGTM

**Pull request merged**
