### PR TITLE
Coherence

### PR DESCRIPTION
**Pull request by paulaltin**
This branch adds two new plot types: coherence spectrograms and coherence spectra, which are specified in the configuration file with a comma-separated pair of channels.

At the moment, the coherence spectra are obtained simply by averaging the spectrograms, in the same way as the normal spectra are. This gives a result which is qualitatively useful but quantitatively incorrect, particularly at low coherence values. Should be fixed in a later update.

One minor bug remains: the legend of a coherence spectrum only shows the first channel used, not both. The second commit attempted to fix this by overriding the _parse_labels method of the SpectrumDataPlot class and setting the name attribute of the spectrum manually in data.py, but this didn't work.

### CODE REVIEW

**Comment by paulaltin** [comment]
Spectra are now done properly by averaging each component spectrogram and then calculating the coherence as Cxy**2 / (Cxx*Cyy). The legend bug is also fixed.

**Comment by duncanmmacleod** [comment]
@paulaltin: I randomly tried to run a day with no segments, and came across this bug:

```
$ gw_summary gps 'Jan 1 2015' 'Jan 2 2015' --config-file longtest.ini --verbose
...
Traceback (most recent call last):
  File "/home/duncan.macleod/.local/bin/gw_summary", line 5, in <module>
    pkg_resources.run_script('gwsumm==0.0.0.dev1087', 'gw_summary')
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/setuptools-4.0.1-py2.6.egg/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/setuptools-4.0.1-py2.6.egg/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/mnt/home2/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/EGG-INFO/scripts/gw_summary", line 840, in <module>
    datafind_error=opts.on_datafind_error, **cache)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/tabs/data.py", line 395, in process
    **stateargs)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/tabs/data.py", line 519, in process_state
    **fftparams)
  File "<string>", line 2, in get_coherence_spectrograms
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 93, in use_segmentlist
    return f(arg1, segments, *args, **kwargs)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 1285, in get_coherence_spectrograms
    datafind_error=datafind_error, **fftparams)
  File "<string>", line 2, in get_coherence_spectrogram
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 93, in use_segmentlist
    return f(arg1, segments, *args, **kwargs)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 838, in get_coherence_spectrogram
    return_components=return_components, **fftparams)
  File "<string>", line 2, in _get_coherence_spectrogram
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 93, in use_segmentlist
    return f(arg1, segments, *args, **kwargs)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/data.py", line 874, in _get_coherence_spectrogram
    s = segments[0].start
IndexError: list index out of range
```

can you have a go at working around that?

**Comment by duncanmmacleod** [comment]
Also, can you please change the type attributes for the new classes to use a `-` delimiter, rather than `_`? Just for consistency.

**Comment by duncanmmacleod** [comment]
Next, I came across problems running a standard summary configuration (i.e. without any coherence plots) that did include Rayleigh plots, which were rejected on your build as follows:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 232, in _bootstrap
    self.run()
  File "/usr/lib64/python2.6/multiprocessing/process.py", line 88, in run
    self._target(*self._args, **self._kwargs)
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/tabs/data.py", line 587, in process_image
    plot.process()
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/plot/builtin.py", line 373, in process
    self._process()
  File "/home/duncan.macleod/.local/lib/python2.6/site-packages/gwsumm-0.0.0.dev1087-py2.6.egg/gwsumm/plot/builtin.py", line 422, in _process
    raise ValueError('Unrecognized type in SpectrumDataPlot')
ValueError: Unrecognized type in SpectrumDataPlot
```

since they had the type 'rayleigh-spectrum', similarly for spectrograms. I would like to propose the following modification of your code to naively pass through any non-coherence plots as they would have done before:

```diff
diff --git a/gwsumm/plot/builtin.py b/gwsumm/plot/builtin.py
index f27c7b5..2a676ee 100644
--- a/gwsumm/plot/builtin.py
+++ b/gwsumm/plot/builtin.py
@@ -275,14 +275,12 @@ class SpectrogramDataPlot(TimeSeriesDataPlot):
         else:
             valid = SegmentList([self.span])
 
-        if self.type is 'spectrogram':
-            specgrams = get_spectrogram(channel, valid, query=False,
-                                        format=sdform)
-        elif self.type is 'coherence_spectrogram':
+        if self.type == 'coherence_spectrogram':
             specgrams = get_coherence_spectrogram(self.channels, valid,
                                                   query=False)
         else:
-            raise ValueError('Unrecognized type in SpectrogramDataPlot')
+            specgrams = get_spectrogram(channel, valid, query=False,
+                                        format=sdform)
 
         # calculate ratio spectrum
         if len(specgrams) and (ratio in ['median', 'mean'] or
@@ -414,12 +412,10 @@ class SpectrumDataPlot(DataPlot):
                 refs[-1][key[len(refkey)+1:]] = self.pargs.pop(key)
 
         # add data
-        if self.type is 'spectrum':
-            iterator = zip(self.channels, plotargs)
-        elif self.type is 'coherence_spectrum':
+        if self.type == 'coherence_spectrum':
             iterator = zip(self.channels[0::2], self.channels[1::2], plotargs)
         else:
-            raise ValueError('Unrecognized type in SpectrumDataPlot')
+            iterator = zip(self.channels, plotargs)
 
         for tuple in iterator:
             channel = tuple[0]
@@ -431,12 +427,12 @@ class SpectrumDataPlot(DataPlot):
             else:
                 valid = SegmentList([self.span])
 
-            if self.type is 'spectrum':
-                data = get_spectrum(str(channel), valid, query=False,
-                                    format=sdform)
-            elif self.type is 'coherence_spectrum':
+            if self.type == 'coherence_spectrum':
                 data = get_coherence_spectrum([str(channel), str(channel2)], va
                                               format=sdform)
+            else:
+                data = get_spectrum(str(channel), valid, query=False,
+                                    format=sdform)
 
             # anticipate log problems
             if self.pargs['logx']:
```

**Comment by duncanmmacleod** [comment]
So, for reference, the above problem with Rayleigh plots is the only problem I have found in using the coherence-patched code to produce non-coherence results.

**Comment by paulaltin** [comment]
@duncanmmacleod Thanks for the bug reports. Should all be fixed now.

**Comment by paulaltin** [comment]
When changing the `type` attributes to use hyphens, it occurred to me I may have misinterpreted what the `data` attributes represent – should they actually be the underlying data types, i.e. should `CoherenceSpectrogramDataPlot` have `data = 'spectrogram'` (`plot/builtin.py` l.345) and `CoherenceSpectrumDataPlot` have `data = 'spectrum'` (`plot/builtin.py` l.520)?

**Comment by duncanmmacleod** [comment]
@paulaltin: the `data` attribute of a plot is used to inform the `DataTab.process` method how it should attempt to generate the data for this plot ahead of time. All plots with `Plot.data == 'timeseries'` invoke a call to `get_timeseries` ([here](https://github.com/gwpy/gwsumm/blob/df0d1715008611d8e06a823a46c26d573992e041/gwsumm/tabs/data.py#L445)), and so on (look at the `DataTab.get_channels` method to see the underlying query against `Plot.data` attribute).

Soooo... if you need to have your plots invoke the specific `get_coherence_spectrogram` method (which you do), you want the `data` attribute to be specific enough to do that, otherwise if they were just `spectrogram` you would end up calculating the PSD spectrogram instead.

**Comment by paulaltin** [comment]
@duncanmmacleod OK, this should all be done now.

**Pull request merged**
