### PR TITLE
Use gwbootstrap 1.3.5

### PR DESCRIPTION
**Pull request by eagoetz**
`gwbootstrap` will be updated to version 1.3.5 to fix a bug in the dropdown alignment. This PR updates the pin and updates a code comment

### CODE REVIEW

**Comment by iaraota** [comment]
Thank you, @eagoetz. Should the `[pyproject.toml](https://github.com/gwpy/gwsumm/blob/master/pyproject.toml)` have updated version of `gwdetchar`?

**Comment by eagoetz** [comment]
> Thank you, @eagoetz. Should the [`pyproject.toml`](https://github.com/gwpy/gwsumm/blob/master/pyproject.toml) have updated version of `gwdetchar`?

Yes, ack! I keep missing that. I'll update that

**Comment by eagoetz** [comment]
@iaraota Please take another look. Ready for review

**Review by iaraota — APPROVED** [review]
LGTM

**Pull request merged**
